const TONES: Record<string, Record<number, string>> = {
    C: {
        1: 'C',
        2: 'Dm',
        3: 'Em',
        4: 'F',
        5: 'G',
        6: 'Am',
        7: 'Bm(b5)',
    },
    D: {
        1: 'D',
        2: 'Em',
        3: 'F#m',
        4: 'G',
        5: 'A',
        6: 'Bm',
        7: 'Cm(b5)',
    },
    E: {
        1: 'E',
        2: 'F#m',
        3: 'G#m',
        4: 'A',
        5: 'B',
        6: 'C#m',
        7: 'D#m(b5)',
    },
    F: {
        1: 'F',
        2: 'Gm',
        3: 'Am',
        4: 'Bb',
        5: 'C',
        6: 'Dm',
        7: 'Em(b5)',
    },
    G: {
        1: 'G',
        2: 'Am',
        3: 'Bm',
        4: 'C',
        5: 'D',
        6: 'Em',
        7: 'F#m(b5)',
    },
    A: {
        1: 'A',
        2: 'Bm',
        3: 'C#m',
        4: 'D',
        5: 'E',
        6: 'F#m',
        7: 'G#m(b5)',
    },
    B: {
        1: 'B',
        2: 'C#m',
        3: 'D#m',
        4: 'E',
        5: 'F#',
        6: 'G#m',
        7: 'A#m(b5)',
    },
};

export {
    TONES,
};
